### ISSUE TITLE
RX-A830 does not support paging

### ISSUE THREAD

**Issue by vooba** [milaq/YCast#12]
I have switched to the dev branch, but this is not  working probably with the RX-A830. It will only display the first 10 records. I think paging was introduced in later products only. 

Would it be possible to en/disable the paging functionality?

**Comment by milaq** [comment]
Hey,

please try the latest dev branch and report back.
I fixed an issue where only the first page was displayed with https://github.com/milaq/YCast/commit/533d4a041d1dc3c6f2af74a86fc1c180ddab2f05.

**Comment by milaq** [comment]
Fixed by https://github.com/milaq/YCast/commit/4accb0bef18a7d2f6bbf312d43898213f4f2a58e
