### ISSUE TITLE
What is roughly needed to implement the bookmark functionality?

### ISSUE THREAD

**Issue by superclass** [milaq/YCast#123]
Hi Milaq,

Nice piece of software. I use it with my recently acquired Yamaha receiver. Can you shed some light on what needs to be done to implement the bookmark stuff? I'd like to help out with that. If you like you can contact me through the website listed on my profile which in turn mentions an e-mail address.

Regards,
André.

**Comment by Essoloani** [comment]
Hello,
Obviously the main project is no longer maintained. Have you looked at ThHanika's fork (request#117)?
Best regards,

**Comment by superclass** [comment]
No I haven't. I'll take a look. Thank you!
