### ISSUE TITLE
Pi-Hole setup for Yamaha ycast

### ISSUE THREAD

**Issue by Abu-Daud** [milaq/YCast#135]
python3 -m ycast -c /etc/stations.yml

[](url)
<img width="738" alt="Screen Shot 2023-12-26 at 1 06 28 PM" src="https://github.com/milaq/YCast/assets/65970176/ab798908-0271-4d3f-b812-1e77bfd57497">

**Comment by drifter75** [comment]
only vtuner.com should be added here pointing to 192.168.0.137.

radioyamaha.vtuner.com & radioyamaha2.vtuner.com records are CNAME records pointing to vtuner.com
