### ISSUE TITLE
Working but no radio station images

### ISSUE THREAD

**Issue by Snipey7** [milaq/YCast#140]
Hallo,

So i got it working on my Marantz NR1605; thank you Milaq for this usefull project!

However it does not load the radio-station images. It appears to be quite similar to issue #131. 

Is this by design? - in that case I need not to look any further for a solution- or should it normally be working? In the latter case, what could be the cause of this?

**Comment by TheBossME** [comment]
For 4 years, I have not noticed any improvements in the application. That's why I've been able to warm to the alternative project from coffeegreg ytuner and use it with very satisfactory results. Greg was also able to implement suggestions promptly. Significantly better performance than ycast.

**Comment by Snipey7** [comment]
Thanks for the suggestion. I'll have a look and see if YTuner provides radio-station images. 

Besides this YCast is working OK for me.
