### ISSUE TITLE
Progress report of ycast as of commit ed6baa6...(Aug-18-2019)

### ISSUE THREAD

**Issue by Zenith-Nadir** [milaq/YCast#15]
Hi Micha,
UPDATE_as of Aug-18th-2019 9:50 AM CEDT(-Central European Daylight Saving Time)
This is my progress report to let you know regarding your project.
I have tested: Latest commit ed6baa6 from 10 hours ago.
Test unit: Yamaha RX-V773
So far everything is working as it should.
I wanted to attach 2 modified files for your review:
I have modified radiobrowser.py to point to my local nginx server instead of radio-browser.info site.
I have also added language section for radiobrowser stations.
Thus radiobrowser.py and server.py have slight modifications and additions, which I am attaching as zipped, for your review and consideration
[radiobrowser.zip](https://github.com/milaq/YCast/files/3512797/radiobrowser.zip)
[server.zip](https://github.com/milaq/YCast/files/3512798/server.zip)

Otherwise the ycast project is excelling.
Fantastic job!
I hope quite a few people will benefit from this.
Also, segler-alex of radio-browser.info has mentioned ycast project on his web pages.
Thanks.
Sincerely,
Z-N

**Comment by milaq** [comment]
Thanks again for your feedback and the nice words :+1: 

I added your proposed language listing feature to the dev branch.
See https://github.com/milaq/YCast/commit/1a51bd195c334430c5c5a37a3a29c570592cc91f

Also, I added a new enhancement issue for changing the Radiobrowser URL for self-hosted Radiobrowser deployments. See https://github.com/milaq/YCast/issues/16

Cheers mate
