### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by geotom** [milaq/YCast#2]
Was thinking about the same idea today and a little search revealed your project.

My idea would be to create a general media collections server, that you could redirect your Yamaha and other vTuner consumers to. The server would allow adding new streaming sources to the collection by plugins that for instance allow self defined media urls (like your projects does) but also proxying other online services that provide streamable content.

On the client side, output plugins would provide a similar categorisation filter like vTunter by interest/region/etc., do caching etc.
The VTuner style API would be just one of several output APIs to serve the media collection to more than one type of consumer (Yamaha).

So far only an idea. Time will tell how much time I can spend on this ;-)

**Comment by milaq** [comment]
Hey there,

thanks for your kind words.
Sounds like a great idea :)

Unfortunately I am quite busy with RL and a few sideprojects. So my free time is quite limited at the moment.
But I'd be interested in the possible outcome of your project. So please let me know how it went.
Maybe I have some time to spare in the future but I can't promise you that.

Also, feel free to contact me via Email if you have any updates on this :+1:
