### ISSUE TITLE
Confirmed: Onkyo TX-NR616 

### ISSUE THREAD

**Issue by daniel-k** [milaq/YCast#29]
Briefly tested: can play radio stations from the list and the station image is correctly displayed in the app. So I guess everything works properly :+1: Thank you!

# Test environment:

YCast in Docker container:
```
FROM python:3-alpine
RUN apk update && apk add build-base zlib-dev jpeg-dev
RUN pip install ycast
ENTRYPOINT [ "python", "-m", "ycast" ]
```
```bash
$ sudo docker run --rm -it -p 80:80 ycast -d
```

Local DNS server (configured in router so AV receiver gets it via DHCP):
```bash
$ sudo docker run --rm -it -p 53:53/tcp -p 53:53/udp -e WILDCARD_DNS='vtuner.com=192.168.XXX.XXX' -e DNS_FORWARDER=1.1.1.1 -e ALLOW_RECURSION='192.168.XXX.0/24,127.0.0.1' cytopia/bind
```

**Comment by milaq** [comment]
Nice, thanks for the report! :+1: 

See https://github.com/milaq/YCast/commit/e17dff463ae89d58538054cfe1ac93efb14cfe45
