### ISSUE TITLE
Debug mode: off even with "-d" option

### ISSUE THREAD

**Issue by blogmotion** [milaq/YCast#32]
Hello and thank you for developing ycast :)

When I start ycast with debug option :

`ExecStart=/usr/bin/python3 -m ycast -l 192.168.0.14 -p 8010 -c /home/pi/ycast/stations.yml -d`

Debug seems to stay off :
```
 systemd[1]: Started YCast internet radio service.
python3[13623]: 2020-02-10 00:11:52 INFO: YCast (1.0.0) server starting
python3[13623]:  * Serving Flask app "ycast.server" (lazy loading)
python3[13623]:  * Environment: production
python3[13623]:    WARNING: This is a development server. Do not use it in a production deployment.
python3[13623]:    Use a production WSGI server instead.
python3[13623]:  * Debug mode: off # <<< HERE, WHY OFF ?
```
But debug is working in terminal. Maybe just a display issue ? or maybe just flask debug mode and not associated with ycast ?

**Comment by milaq** [comment]
Yes, that is intended and, as you guessed correctly, indicates the flask debug mode only.

Thanks for the report though.
