### ISSUE TITLE
[Hardware Report] Onkyo PR-SC5509 (TX-NR5009) working

### ISSUE THREAD

**Issue by M-Schoeler** [milaq/YCast#41]
Hi, i checked with my Onkyo PR-SC5509 and it works without any issues.
Perhaps this applies to the whole Onkyp (x)xx9 series (model year 2011).

**Comment by milaq** [comment]
Hi,
Thank you very much for reporting!
:+1: 

See https://github.com/milaq/YCast/commit/aa0771048b44f3ba43939827d49d703dc3431e9d

We need to wait for a few more confirmed devices from that model line though before greenlighting the whole batch.
We had it in the past that some models worked while some from the same line didn't.
