### ISSUE TITLE
[Hardware Report] Marantz NR1605 working

### ISSUE THREAD

**Issue by Apolio1** [milaq/YCast#43]
Your project helped my a lot! It works with a Marantz NR1605.

**Comment by Luilutin** [comment]
Same with NR1506

**Comment by 2003flo** [comment]
I dont understand how yCast works. Does it Provide Browsing Radio stations on the Receiver of is it just a way to Play Stored favorites?

**Comment by Luilutin** [comment]
It provides radio station list from http://www.radio-browser.info/gui/#!/ . You can also add favorite stations to file.

**Comment by 2003flo** [comment]
Can you browse the stations via the marantz App?

**Comment by Luilutin** [comment]
It replaces vTuner. You can search and select stations with receiver and tv.

**Comment by 2003flo** [comment]
Anyone tried to install on Fritzbox?

**Comment by milaq** [comment]
> Your project helped my a lot! It works with a Marantz NR1605.
> Same with NR1506

Hi,
glad you like it :)

Thank you very much for reporting!
:+1: 

See https://github.com/milaq/YCast/commit/aa0771048b44f3ba43939827d49d703dc3431e9d
