### ISSUE TITLE
Marantz NA8005 works

### ISSUE THREAD

**Issue by guy-middleton** [milaq/YCast#46]
Great software, thanks for building this.

FYI network setup:
- Linksys NRT1900ACS
- Raspberry Pi 4
- dnsmasq to spoof `denon.vtuner.com`
- nginx
- ycast

**Comment by milaq** [comment]
Hi,
thank you very much for reporting!
:+1: 

See https://github.com/milaq/YCast/commit/46ade04621470a6c0abe77958f8fc6a4abf81af0
