### ISSUE TITLE
Success: RX-V3067

### ISSUE THREAD

**Issue by anset** [milaq/YCast#52]
Works without issue.

Thanks! :)

**Comment by rapinga0** [comment]
Hey
Could you share more info about your configuration or the steps you did?. I managed to make mine work for a RX-A730 and a RX-A1020, but the RX-V3067 seems to refuse my settings and keep saying "not connected".
Thanks for the help

**Comment by anset** [comment]
I did not do anything specific: just downloaded the code and ran it. 
Hardest past was "fixing the DNS" to make sure it resolved the vtuner domains locally. 
I did redirect both radioyamaha.vtuner.com and radioyamaha2.vtuner.com. But that's about it.

Sorry I cannot help more.

**Comment by milaq** [comment]
Thanks for reporting :1st_place_medal: 
See https://github.com/milaq/YCast/commit/c7a30860f7c816feb6167d1ca2ecd713b2eb4583
