### ISSUE TITLE
Switch to new API

### ISSUE THREAD

**Issue by dzikidzik** [milaq/YCast#54]
Hello @milaq 
Thank you for quite interesting vtuner alternative, I am trying to use YCast with Marantz Consolette and found that new stations added to radio-browser.info are not showing up on the device, do you think it might be linked with fact that YCast is using old API `http://www.radio-browser.info/webservice/json/` and radio-browser introduced new API?

Do you have any plans to update YCast and change it to new API `https://api.radio-browser.info/`

```
The api endpoints at www.radio-browser.info/webservice will be taken down at August 1. of 2020.
```

Thank you for your work.

**Comment by milaq** [comment]
Thanks for the headsup :+1: 

First of August is a very short window in my opionion, but we'll have to accept it.
I'll set this issue as high prio.

**Comment by feidhlimoneill** [comment]
verified this means i can now browse stations again on marantz m-cr610

**Comment by milaq** [comment]
Finally, I had some time to implement the latest changes *phew*

The Radiobrowser API should be working again with:
https://github.com/milaq/YCast/commit/0a2aaa163d259a8b73813418e358f715ace4d4cd

I'll push a new version today.

Again, thanks for the report :+1:
