### ISSUE TITLE
Can confirm: Yamaha RX-A820

### ISSUE THREAD

**Issue by pafodie** [milaq/YCast#6]
It worked well with my Yamaha RX-A820. Thanks for sharing your code!

**Comment by vooba** [comment]
It worked well with my Yamaha RX-A830 too. Thanks for the great work!

**Comment by milaq** [comment]
Thanks for reporting guys.

See https://github.com/milaq/YCast/commit/787bf0a6e9553b1ac84557295b0c97d57242bc2c
