### ISSUE TITLE
SOLUTION: Important Note - HINT Re: "ACCESS ERROR"

### ISSUE THREAD

**Issue by Zenith-Nadir** [milaq/YCast#8]
Hi to All Interested:
In previous posts I was frequently receiving, and thus mentioning "ACCESS ERROR" on my Yamaha RX-V773.
And problems with non-ASCII extended characters in folders and station names.
Turns out it is/was related to python version and flask version running on the ycast running system.
The ycast project mentions: >>>Dependencies: Python version: 3<<<
However, my system was running by default python 2.7, which has problems with UTF-8 character-set, which was mitigated in python3.
And thus by default system also installed flask based on python 2.7.
This situation was causing constant "ACCESS ERROR(s)", when trying to browse folders or stations containing UTF-8 charset.
I finally managed to correct these issues (errors), by installing flask running on python3.
For those not sure "what and how to", this is how you might try to mitigate/remedy some of the "ACCESS ERROR(s)".
Check your python version:
cmd: (Uppercase=Capital "V")
`:~$ python -V`
`Python 2.7.15+`
`:~$ python3 -V`
`Python 3.6.8`
to install python3 flask on Ubuntu (my 18.04LTS) do:
`:~$ sudo apt install python3-pip`
(this one below without sudo, according to docs from internet)
`:~$ pip3 install Flask`
and finally from ycast folder run:
`:~$ python3 -m ycast -c stations.yml -p 8010`
or something similar depending what ver of ycast you are running (I am currently using dev branch for radiobrowser as well).
I Hope this might help and clarify some errors you might encounter.
This is probably not a solution for tuner authentication and mac errors or DNS errors; this is only pertaining with stations lists.
Z-N

**Comment by milaq** [comment]
Thanks for the headsup :+1: 

I added a minimum version check. See https://github.com/milaq/YCast/commit/bfa203d160f7c739c2703dcc0225ff4696ed4728

I'll leave this issue open for a bit for others to notice.
